apiVersion: v1
kind: Service
{{- with .Values.service }}
metadata:
  name: {{ $.Release.Name }}-svc
  labels:
    app: {{ $.Release.Name }}
spec:
  selector:
    app: {{ $.Release.Name }}
  ports:
    - port: {{ $.Values.service.ports.port }}
      targetPort: {{ $.Values.service.ports.targetPort }}
      protocol: {{ $.Values.service.ports.protocol }}
  type: ClusterIP
{{- end }}
