apiVersion: v1
kind: Service
{{- with .Values.service }}
metadata:
  name: {{ $.Release.Name }}-svc
  labels:
    app: {{ $.Release.Name }}
spec:
  selector:
    app: {{ $.Release.Name }}
  ports:
    - name: http
      port: {{ .ports.port }}
      targetPort: {{ .ports.targetPort }}
      protocol: {{ .ports.protocol }}
{{- end }}
