apiVersion: v1
kind: Service
{{- with .Values.service }}
metadata:
  name: {{ $.Release.Name }}-svc
  labels:
    app: {{ $.Release.Name }}
spec:
  selector:
    app: {{ $.Release.Name }}
  ports:
    - port: {{ .type.clusterIP.port }}
      targetPort: {{ .type.clusterIP.targetPort }}
      protocol: {{ .type.clusterIP.protocol }}
  type: ClusterIP
{{- end }}
